name: thegeekgypsy_desk
description: The Geek Gypsy Desk
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/favicon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21




flutter:
  uses-material-design: true

  assets:
    - assets/